name: Sqitch Lint Check

on:
  push:
    paths:
      - 'deploy/**'
      - 'sqitch.plan'
      - 'scripts/sqitch_lint.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Sqitch Plan Lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          pip install sqlparse

      - name: Run linter
        run: |
          python3 scripts/sqitch_lint.py
