name: Sqitch CI/CD for PostgreSQL

on:
  push:
    paths:
      - 'deploy/**'
      - 'revert/**'
      - 'verify/**'
      - 'sqitch.plan'
      - '.github/workflows/**'
      - '.secrets'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug DB_URI
      run: |
        echo "::notice ::DB_URI from secrets = $DB_URI"env | grep DB_URI || echo "DB_URI not found in env"
   
    - name: Print DB_URI
      run: echo $DB_URI

    - name: Install Sqitch and PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y sqitch libdbd-pg-perl postgresql-client

    - name: Deploy migrations
      run: |
        sqitch deploy $DB_URI

    - name: Verify deployment
      run: |
        sqitch verify $DB_URI

  rollback:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Sqitch and PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y sqitch libdbd-pg-perl postgresql-client

    - name: Revert latest change
      run: |
        sqitch revert db:pg:${{ secrets.DB_URI }} -y
