name: Lint SQL

on: [push, pull_request]

jobs:
  lint_sql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SQLFluff
      run: pip install sqlfluff
    - name: Run SQLFluff Lint
      run: sqlfluff lint . --dialect postgres
